image: node:14.15.4

pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install --no-package-lock
            - npm run deploy

